---
title: "Figure 2.17"
author: "Aishwarya Sivaramakrishnan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/Aishwarya S/OneDrive - The University of Chicago/Advance Illinois/GraphsToReplicate/Figure 2.17") 
library(dplyr)
library(ggplot2)
library(scales)
library(stringr)
library(scales)
library(tidyverse)
library(tidyr)
```

```{r}
raw_import <- read.csv("usa_00004.csv.gz")
```

```{r}
filtered <- raw_import %>%
  filter(YEAR == 2022,
         AGE > 24,
         STATEFIP == 17)

filtered <- filtered %>%
  mutate(Education = case_when(
    EDUCD %in% c(002:061) ~ "Less than a High School Diploma",
    EDUCD %in% c(062:064) ~ "High School Diploma",
    EDUCD %in% c(065:080) ~ "Some College, No Degree",
    EDUCD %in% c(081:083) ~ "Associate Degree",
    EDUCD == 101 ~ "Bachelor's Degree",
    EDUCD == 114 ~ "Master's Degree",
    EDUCD == 116 ~ "Doctoral Degree",
    EDUCD == 115 ~ "Professional Degree"
  ))
```

```{r}
medicaid_result <- filtered %>%
  group_by(Education) %>%
  summarize(
    Total = n(),
    ReceivedMedicaid = sum(HINSCAID == 1),
    MedicaidPercentage = (ReceivedMedicaid / Total) * 100
  )

foodstamps_result <- filtered %>%
  group_by(Education) %>%
  summarize(
    Total = n(),
    ReceivedFoodStamps = sum(FOODSTMP == 1),
    FoodStampsPercentage = (ReceivedFoodStamps / Total) * 100
  )

```

```{r}
education_colors <- c(
  "Less than a High School Diploma" = "#03ADCB", 
  "High School Diploma" = "#AAD6D4", 
  "Some College, No Degree" = "#0F6B8D", 
  "Associate Degree" = "#C3B39E", 
  "Bachelor's Degree" = "#F48437", 
  "Master's Degree" = "#FFB172", 
  "Doctoral Degree" = "#CC770B",
  "Professional Degree" = "#C04822"
)
```

```{r}
combined_results <- left_join(medicaid_result, foodstamps_result, by = "Education")

long_data <- combined_results %>%
  select(Education, MedicaidPercentage, FoodStampsPercentage) %>%
  pivot_longer(
    cols = -Education,
    names_to = "Program",
    values_to = "Percentage"
  ) %>%
  mutate(Program = str_replace(Program, "Percentage", ""))

long_data$Education <- factor(
  long_data$Education,
  levels = c(
    "Less than a High School Diploma",
    "High School Diploma",
    "Some College, No Degree",
    "Associate Degree",
    "Bachelor's Degree",
    "Master's Degree",
    "Doctoral Degree",
    "Professional Degree"
  )
)


ggplot(long_data, aes(x = Program, y = Percentage, fill = Education)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.7)) +
  scale_fill_manual(values = education_colors) +
  labs(
    title = "Percentage of Individuals Age 25\
    and Older Participating in Public Assistance Programs\
    by Education Level in Illinois, 2022",
    fill = "Education Level",
    x = "",
    y = "Participation Rate"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    legend.position = "bottom",
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 9)
  ) +
  scale_y_continuous(labels = percent_format(scale = 1),
                     breaks = seq(0, 50, by = 10), 
                     limits = c(0, 50))
   

```

```{r}
# Rename the percentage columns to a common name
medicaid_result$Program <- 'Medicaid'
medicaid_result$Percentage <- medicaid_result$MedicaidPercentage

foodstamps_result$Program <- 'SNAP'
foodstamps_result$Percentage <- foodstamps_result$FoodStampsPercentage

# Select only the necessary columns to combine
medicaid_result <- medicaid_result %>% select(Education, Program, Percentage)
foodstamps_result <- foodstamps_result %>% select(Education, Program, Percentage)

# Combine the two data frames
combined_results <- rbind(medicaid_result, foodstamps_result)

# Ensure the Education factor levels match the order you want in the plot
combined_results$Education <- factor(
  combined_results$Education,
  levels = c(
    "Less than a High School Diploma",
    "High School Diploma",
    "Some College, No Degree",
    "Associate Degree",
    "Bachelor's Degree",
    "Master's Degree",
    "Doctoral Degree",
    "Professional Degree"
  )
)

```

