---
title: "Graph_2.19A"
author: "Amartya Kumar Sinha"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/cloud/project/GraphsToReplicate/Graph2.19") 
library(dplyr)
library(ggplot2)
library(scales)
library(stringr)
library(scales)
library(tidyverse)
library(tidyr)
```

```{r}
raw_import_219A <- read.csv("cps_00011.csv.gz")
```

```{r}
filtered_19A <- raw_import_219A %>%
  filter(MONTH == 9,
         AGE > 24,
         VLSTATUS == 1 | VLSTATUS == 2)

filtered_19A <- filtered_19A %>%
  mutate(Education = case_when(
    EDUC %in% c(002:072) ~ "Less than a High School Diploma",
    EDUC == 073 ~ "High School Diploma",
    EDUC %in% c(080:090, 100, 110, 120:122) ~ "Some College, No Degree",
    EDUC %in% c(091:092) ~ "Associate Degree",
    EDUC == 111 ~ "Bachelor's Degree",
    EDUC == 123 ~ "Master's Degree",
    EDUC == 125 ~ "Doctoral Degree",
    EDUC == 124 ~ "Professional Degree"
  ))
```

```{r}
volunteer_rates <- filtered_19A %>%
  group_by(SEX, Education, VLSTATUS) %>%
  summarise(count = n()) %>%
  mutate(volunteer_rate = ifelse(VLSTATUS == 1, count, 0) / sum(count) * 100) %>%
  filter(VLSTATUS == 1) # Only keep volunteer entries

# Convert SEX in volunteer_rates to character
volunteer_rates$SEX <- as.character(volunteer_rates$SEX)

# Calculate total counts for each education level
total_counts <- filtered_19A %>%
  group_by(Education) %>%
  summarise(total_count = n(), .groups = "drop")

# Calculate volunteering rates by education level (ignoring gender)
volunteer_rates_all <- filtered_19A %>%
  mutate(SEX = "All") %>% # Add a new column 'SEX' with value 'All'
  group_by(SEX, Education, VLSTATUS) %>%
  summarise(count = n(), .groups = "drop") %>%
  left_join(total_counts, by = "Education") %>%
  mutate(volunteer_rate = ifelse(VLSTATUS == 1, count, 0) / total_count * 100) %>%
  filter(VLSTATUS == 1) # Only keep volunteer entries

# Combine the two data frames
volunteer_rates_combined <- bind_rows(volunteer_rates, volunteer_rates_all)
```

```{r}
# Plotting the graph
education_colors <- c(
  "Less than a High School Diploma" = "#03ADCB", 
  "High School Diploma" = "#AAD6D4", 
  "Some College, No Degree" = "#0F6B8D", 
  "Associate Degree" = "#C3B39E", 
  "Bachelor's Degree" = "#F48437", 
  "Master's Degree" = "#FFB172", 
  "Doctoral Degree" = "#CC770B",
  "Professional Degree" = "#C04822"
)

volunteer_rates_combined$Education <- factor(
  volunteer_rates_combined$Education,
  levels = c("Less than a High School Diploma",
    "High School Diploma",
    "Some College, No Degree",
    "Associate Degree",
    "Bachelor's Degree",
    "Master's Degree",
    "Doctoral Degree",
    "Professional Degree"))

ggplot(volunteer_rates_combined, aes(x = factor(SEX), y = volunteer_rate, fill = Education), width = 24, height = 20) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = sprintf("%.1f", volunteer_rate, 1)), 
            position = position_dodge(width = 0.9), 
            vjust = -0.5, 
            size = 2) +
  scale_fill_manual(values = education_colors) +
            labs(title = "Percentage of Individuals Age 25 and Older\
                 Who Volunteered,\
                 by Gender and Education Level in Illinois, 2021",
       x = "Gender",
       y = "Volunteering Rate (%)",
       fill = "Education Level") +
  theme_minimal() +
 theme(
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
    axis.title.x = element_blank(),
    axis.text.x = element_text(hjust = 1),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    legend.position = "bottom",
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 5)
  ) + 
  scale_x_discrete(labels = c("1" = "Male", "2" = "Female", "all" = "All"))

```

```{r}
# Create a new variable for age ranges
filtered_19A$AgeRange <- cut(filtered_19A$AGE, 
                              breaks = c(24, 34, 54, 64, Inf), 
                              labels = c("25-34", "35-54", "55-64", "65 and older"), 
                              include.lowest = TRUE, 
                              right = FALSE)

# Calculate total counts for each age range and education level
total_counts <- filtered_19A %>%
  group_by(AgeRange, Education) %>%
  summarise(total_count = n(), .groups = "drop")

# Calculate volunteering rates by age range and education level
volunteer_rates_age <- filtered_19A %>%
  group_by(AgeRange, Education, VLSTATUS) %>%
  summarise(count = n(), .groups = "drop") %>%
  left_join(total_counts, by = c("AgeRange", "Education")) %>%
  mutate(volunteer_rate = ifelse(VLSTATUS == 1, count, 0) / total_count * 100) %>%
  filter(VLSTATUS == 1) # Only keep volunteer entries
```

```{r}
# Plotting the graph
ggplot(volunteer_rates_age, aes(x = AgeRange, y = volunteer_rate, fill = Education)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = sprintf("%.1f", volunteer_rate)), 
            position = position_dodge(width = 0.9), 
            vjust = -0.5, 
            size = 2) +
  labs(title = "Percentage of Individuals Age 25 and Older\
       Who Volunteered, \nby Age and Education Level, 2021",
       x = "Age Range",
       y = "Volunteering Rate (%)",
       fill = "Education Level") +
  theme_minimal() +
   theme(
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
    axis.title.x = element_blank(),
    axis.text.x = element_text(hjust = 1),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    legend.position = "bottom",
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 5)
  )
```