---
title: "Figure 2.15A"
author: "Aishwarya Sivaramakrishnan"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/Amartya Kumar Sinha/OneDrive - The University of Chicago/Miscellaneous/Personal/AdvIllinois_Analysis/GraphsToReplicate/Graph 2.15A") 
library(dplyr)
library(ggplot2)
library(scales)
library(stringr)
library(scales)
library(tidyverse)
library(tidyr)
```

```{r}
raw_import_215A <- read.csv("cps_00004.csv.gz")

```

```{r}
filtered_215A <- raw_import_215A %>%
  filter(AGE > 24,
         STATEFIP == 17,
          WKSTAT%in% c(10,11,12))

filtered_215A <- filtered_215A %>%
 mutate(Education = case_when(
 EDUC %in% c(2:71) ~ "Less than a High School Diploma",
 EDUC == 73 ~ "High School Diploma",
 EDUC %in% c(80:81) ~ "Some College No Degree",
 EDUC %in% c(91:92) ~ "Associate's Degree",
 EDUC == 111 ~ "Bachelor's Degree",
 EDUC %in% c(123:125) ~ "Advanced Degree"
 ))
```

```{r}
ins_coverage <- filtered_215A%>%
  group_by(Education, YEAR) %>%
  summarize(Total = n(),
    EmpInsurance = sum(PAIDGH %in% c(20,21,22)),
    PercentageCovered = (EmpInsurance / Total) * 100)
```

```{r}
education_colors <- c(
  "Less than a High School Diploma" = "#03ADCB", 
  "High School Diploma" = "#AAD6D4", 
  "Some College, No Degree" = "#0F6B8D", 
  "Associate Degree" = "#C3B39E", 
  "Bachelor's Degree" = "#F48437", 
  "Master's Degree" = "#FFB172", 
  "Doctoral Degree" = "#CC770B",
  "Professional Degree" = "#C04822"
)

filtered_215A$Education <- factor(
  filtered_215A$Education,
  levels = c("Less than a High School Diploma",
    "High School Diploma",
    "Some College, No Degree",
    "Associate Degree",
    "Bachelor's Degree",
    "Master's Degree",
    "Doctoral Degree",
    "Professional Degree"))
```

```{r}
ggplot(ins_coverage, aes(x = YEAR, y = PercentageCovered, fill = Education)) +
  geom_bar(stat = "identity", position = position_dodge(width = 10)) +
  geom_text(aes(label = sprintf("%.1f", PercentageCovered)), 
            position = position_dodge(width = 10), 
            vjust = -0.5, size = 3, color = "black") + 
  scale_fill_manual(values = education_colors) +
  labs(
    title = "Employer-Provided Group Health Insurance Coverage\
    Among Full-Time Year-Round Workers Age 25 and Older\
    by Education Level in Illinois, 2001, 2011, and 2021",
    fill = "Education Level",
    x = "",
    y = "Percentage Covered"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
    axis.title.x = element_blank(),
    axis.text.x = element_text(hjust = 1),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    legend.position = "bottom",
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 5)
  )
```

