---
title: "2.14_Attempt3"
output: html_document
date: "2024-01-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/Amartya Kumar Sinha/OneDrive - The University of Chicago/Miscellaneous/Personal/AdvIllinois_Analysis/GraphsToReplicate/Graph2.14") 
library(dplyr)
library(ggplot2)
```


```{r}
raw_import <- read.csv("cps_00003.csv.gz")
```

```{r}
filtered <- raw_import %>%
  filter(AGE > 24,
         STATEFIP == 17,
         PENSION %in% c(1, 2, 3),
         WKSTAT%in% c(10,11,12))

```

```{r}
filtered <- filtered %>%
  mutate(Private = ifelse(CLASSWKR == 21, 1, 0))

filtered <- filtered %>%
  mutate(Government = ifelse(CLASSWKR %in% c(25, 27, 28), 1, 0))
```

```{r}
filtered <- filtered %>%
  mutate(Education = case_when(
    EDUC %in% c(2:71) ~ "Less than a High School Diploma",
    EDUC == 73 ~ "High School Diploma",
    EDUC %in% c(80:81) ~ "Some College No Degree",
    EDUC %in% c(91:92) ~ "Associate's Degree",
    EDUC == 111 ~ "Bachelor's Degree",
    EDUC %in% c(123:125) ~ "Advanced Degree"
  ))
```


```{r}
percentages <- filtered %>%
  group_by(Education, Private, Government) %>%
  summarise(Total = n(),
            OfferedPension = sum(PENSION %in% c(2, 3))) %>%
  ungroup() %>%
  mutate(PercentageOffered = (OfferedPension / Total) *100)
```

```{r}
# Grouped by education level

ggplot(percentages , aes(x=Education, y=PercentageOffered, fill=factor(ifelse(Private==1, "Private", "Government")))) +
  geom_bar(stat="identity", position=position_dodge(width=0.9)) +
  labs(fill="Sector") +
  theme_minimal() +
  scale_fill_manual(values=c("lightblue","burlywood")) +
  ylab("Percentage Offered") +
  xlab("Education Level") +
  scale_y_continuous(limits = c(0, 100)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```
```{r}
# Grouped by job sector, without percentages

ggplot(percentages, aes(x = Education, y = PercentageOffered, fill = factor(ifelse(Private == 1, "Private", "Government")))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(fill = "Sector") +
  theme_minimal() +
  scale_fill_manual(values = c("lightblue", "burlywood")) +
  ylab("Percentage Offered") +
  xlab("Education Level") +
  scale_y_continuous(limits = c(0, 100)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  facet_grid(. ~ factor(ifelse(Private == 0, "Government", "Private")), scales = "free_x", space = "free_x")
```
```{r}
# Grouped by job sector, with percentages

ggplot(percentages, aes(x = Education, y = PercentageOffered, fill = factor(ifelse(Private == 1, "Private", "Government")))) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = sprintf("%.2f%%", PercentageOffered)),
            position = position_dodge(width = 0.9), vjust = -0.5, size = 3) +
  labs(fill = "Sector") +
  theme_minimal() +
  scale_fill_manual(values = c("lightblue", "burlywood")) +
  ylab("Percentage Offered") +
  xlab("Education Level") +
  scale_y_continuous(limits = c(0, 100)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  facet_grid(. ~ factor(ifelse(Private == 0, "Government", "Private")), scales = "free_x", space = "free_x")
```

