---
title: "2.13A"
output: html_document
date: "2024-01-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/Amartya Kumar Sinha/OneDrive - The University of Chicago/Miscellaneous/Personal/AdvIllinois_Analysis/GraphsToReplicate/Graph2.13A") 
library(dplyr)
library(ggplot2)
```

```{r}
raw_2.13 <- read.csv("cps_00010.csv.gz")
```

```{r}
# Filtering data by age and state

filtered_2.13 <- raw_2.13 %>%
  filter(AGE > 24,
         STATEFIP == 17)
```

```{r}
# Categorizing education levels

filtered_2.13 <- filtered_2.13 %>%
  mutate(Education = case_when(
    EDUC %in% c(2:71) ~ "Less than a High School Diploma",
    EDUC == 73 ~ "High School Diploma",
    EDUC %in% c(80:81) ~ "Some College No Degree",
    EDUC %in% c(91:92) ~ "Associate Degree",
    EDUC %in% c(111, 123:125) ~ "Bachelor's degree or higher"))
```

```{r}
# Add dummy variable for unemployment

filtered_2.13 <- filtered_2.13 %>%
  mutate(Unemployment = ifelse(WKSTAT %in% c(50, 60), 1, 0))
```

```{r}
# Calculating unemployment rate

unemployment_rate <- filtered_2.13 %>%
  group_by(YEAR, Education) %>%
  summarise(UnemploymentRate = mean(Unemployment)*100, .groups = "drop") 

```

```{r}
p <- ggplot(unemployment_rate, aes(x = YEAR, y = UnemploymentRate, color = Education)) +
  geom_line() +
  scale_x_continuous(breaks = seq(min(unemployment_rate$YEAR), max(unemployment_rate$YEAR), by = 2)) +
  labs(title = "Unemployment Rate: Individuals 25 and older in Illinois by Education Level (2002 to 2022)",
       x = "Year",
       y = "Unemployment Rate (%)",
       color = "Education Level") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 1), # Center the title
        legend.position = c(0.98, 0.98), 
        legend.justification = c(1, 1), 
        legend.box.just = "right", 
        legend.direction = "vertical",
        legend.box = "vertical",
        legend.margin = margin(4, 4, 4, 4),
        legend.text = element_text(size = 8),
        legend.background = element_rect(fill="white", colour="black", size=0.5))

# Print the plot
print(p)
```






